version: "3.9"

services:
  ml_project:
    build: .
    container_name: pycaret_env
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  streamlit_app:
    build: .
    container_name: streamlit_pycaret
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1     
