services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=retail_db
    ports:
      - '3310:3306'
    volumes: 
      - ./mysqldata:/mysql/data
    env_file: 
      - ./mysql/variables.env

  streamlit:
    build:
      context: ./streamlit_app
    restart: always
    ports:
      - '8501:8501'
    volumes:
      - ./streamlit_app:/app
    working_dir: /app
    command: streamlit run app.py
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
volumes:
  mysqldata:
  mongodata:
