version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: omnileads
      POSTGRES_PASSWORD: omnileads
      POSTGRES_DB: omnileads
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/omnileads
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: